nhsd-exeter/dos-service-fuzzy-search-api

build/automation/var/project.mk
build/docker/mockservice.docker-compose.yml
test/contract/Makefile
test/contract/README.md
test/contract/Test.postman_collection.json
test/contract/docker.postman_environment.json
test/contract/mappings/hello-world.json
test/contract/postman.postman_environment.json

This PR has been created as an effect of running the `make project-create-contract-test` command and provides a template for initiating contract test suite implementation. Please, see `test/contract/README.md` for more details.

Contract test

---

application/app/src/main/java/uk/nhs/digital/uec/api/controller/FuzzyServiceSearchController.java
application/app/src/main/java/uk/nhs/digital/uec/api/model/ApiSearchParamsResponse.java
application/app/src/main/java/uk/nhs/digital/uec/api/model/ApiSearchResultsResponse.java
application/app/src/main/java/uk/nhs/digital/uec/api/model/ApiSuccessResponse.java
application/app/src/test/java/uk/nhs/digital/uec/api/controller/FuzzySearchControllerTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/ElasticSearchTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchGeneralErrorsTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchSuccessTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchValidationErrorsTest.java

PR to improve the JSON response from the API as defined in: https://nhsd-confluence.digital.nhs.uk/display/SFDEV/Known+Service+Search

SFD-2349 Improve API JSON response output

---

test/contract/mappings/StringStartsWithCapital.json
test/contract/mappings/address.json
test/contract/mappings/addressPartialString.json
test/contract/mappings/allCaps.json
test/contract/mappings/capitalWithInString.json
test/contract/mappings/nullServices.json
test/contract/mappings/oneService.json
test/contract/mappings/postcode.json
test/contract/mappings/publicName.json
test/contract/mappings/quotes.json
test/contract/mappings/specislCharacter.json
test/contract/mappings/tot.json
test/contract/mappings/totn.json
test/contract/mappings/totnes.json
test/contract/mappings/totnesHospital.json
test/contract/mappings/totnesTrailingSpace.json
test/contract/mappings/twoServices.json

Changes to the json body on all the mappings.

Updates to contract test wiremock mappings for API response output

---

build/automation/var/profile/dev.mk
deployment/stacks/service/base/template/service-search/service-account.yaml
infrastructure/modules/cognito/cognito_pool.tf
infrastructure/modules/elasticsearch/cloudwatch.tf
infrastructure/modules/elasticsearch/elasticsearch.tf
infrastructure/modules/elasticsearch/es_snapshots_role.tf
infrastructure/modules/elasticsearch/locals.tf
infrastructure/scripts/cognito.sh
infrastructure/stacks/authentication/locals.tf
infrastructure/stacks/authentication/main.tf
infrastructure/stacks/roles/data.tf
infrastructure/stacks/roles/locals.tf
infrastructure/stacks/roles/main.tf
infrastructure/stacks/roles/providers.tf
infrastructure/stacks/roles/terraform.tf
infrastructure/stacks/roles/variables.tf

You can ignore the changes in the cognito.sh file. I had to replace the tabs with double spaces to get passed the commit verification messages.

SFD-2789 terraform iam roles for service accounts

---

application/app/pom.xml
application/app/src/test/java/uk/nhs/digital/uec/api/authentication/controller/LoginControllerTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/authentication/service/AuthenticationServiceTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/authentication/util/UtilsTest.java
application/app/src/test/resources/application-local.yaml
documentation/authentication/README.md

SFD-3257 code coverage for login and readme file update

SFD-3257 code coverage for login

---

test/contract/FuzzySearchApiContractTests_collection.json

- Login with valid and invalid credentials as a collection
- Scripts added to extract access and refresh tokens
- Auto save tokens as environment variables

SFD-3170_login_endpoint_test

---

application/app/pom.xml
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/config/SecurityConfig.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/constants/AuthenticationConstants.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/exception/AccessTokenExpiredException.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/filter/AccessTokenFilter.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/filter/TokenEntryPoint.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/service/AuthenticationService.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/util/JwtUtil.java
application/app/src/main/resources/application.yaml
documentation/authentication/README.md

SFD 3177 implement local authorisation

SFD 3177 implement local authorisation

---

build/docker/docker-compose.yml

SFD-3359 Project start fix

---

application/app/src/test/java/uk/nhs/digital/uec/api/service/LocationServiceTest.java

SFD-3480 Code coverage for postcode mapping changes

SFD-3480 Code coverage for postcode mapping changes

---

application/app/src/main/java/uk/nhs/digital/uec/api/controller/FuzzyServiceSearchController.java

Add authorisation to endpoints so that only users who are assigned to the 'FUZZY' Cognito group can access the endpoint.

SFD-XXXX Add authorisation to endpoints

---

build/automation/var/profile/dev.mk
deployment/stacks/application/base/template/kustomization.yaml
infrastructure/stacks/elasticsearch/locals.tf
infrastructure/stacks/roles/locals.tf

Add Splunk logging index and tidy up service tags

SFD-2356 Add Splunk logging index and tidy up service tags

---

application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/AuthServiceTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/ElasticSearchTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchGeneralErrorsTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchSuccessTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchValidationErrorsTest.java
application/app/src/test/resources/application.yaml

SFD-3376 Integration contract test

SFD-3376 Integration contract test

---

build/automation/var/profile/dev.mk
build/automation/var/profile/local.mk

SFD-3376 Adding postcode mapping url for local and dev mk

SFD-3376 Adding postcode mapping url for local and dev mk

---

.github/workflows/code-quality.yml
application/app/pom.xml

SFD 3797 Sonar and jacoco to ignore certain files during code coverage

SFD-3797 Sonar and jacoco to ignore certain files during code coverage

---

build/automation/var/profile/demo.mk
build/automation/var/profile/dev.mk
build/automation/var/profile/prod.mk

SFD-3724 Setting the urls right

SFD-3724 Setting the urls right

---

application/app/pom.xml
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/config/SecurityConfig.java
application/app/src/main/java/uk/nhs/digital/uec/api/config/SwaggerConfig.java
application/app/src/main/java/uk/nhs/digital/uec/api/controller/FuzzyServiceSearchController.java
application/app/src/main/resources/application.yaml

SFD-3827 Swagger documentation changes included

SFD-3827 Swagger documentation changes included

---

application/app/src/main/java/uk/nhs/digital/uec/api/service/impl/ApiUtilsService.java
application/app/src/main/java/uk/nhs/digital/uec/api/service/impl/MockDosServicesUtil.java
application/app/src/test/java/uk/nhs/digital/uec/api/controller/FuzzySearchControllerTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/authentication/controller/EndpointAuthorisationIT.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchSuccessIT.java
application/app/src/test/java/uk/nhs/digital/uec/api/service/ValidationServiceTest.java

SFD-3847 Sonar code quality fixes for code smell added

SFD-3847 Sonar code quality fixes for code smell added

---

application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchGeneralErrorsIT.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchSuccessIT.java
application/app/src/test/java/uk/nhs/digital/uec/api/integration/fuzzysearch/FuzzySearchValidationErrorsIT.java

SFD-3847 Resolving more sonar quality issues

SFD-3847 Resolving more sonar quality issues

---

build/automation/var/profile/test.mk
build/jenkins/Jenkinsfile.development

SFD-3974 Junit test profile created

SFD-3974 Junit test profile created

---

application/app/src/main/java/uk/nhs/digital/uec/api/authentication/config/MockAuthConfig.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/config/SecurityConfig.java
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/constants/SwaggerConstants.java
application/app/src/main/java/uk/nhs/digital/uec/api/controller/FuzzySearchHomeController.java
application/app/src/main/java/uk/nhs/digital/uec/api/controller/FuzzyServiceSearchController.java
application/app/src/main/resources/application.yaml
application/app/src/test/java/uk/nhs/digital/uec/api/controller/FuzzySearchControllerTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/controller/FuzzySearchHomeControllerTest.java
application/app/src/test/resources/application-local.yaml
application/app/src/test/resources/application.yaml

SFD-4032 Dont authenticate certain endpoints and swagger update

SFD-4032 Dont authenticate certain endpoints and swagger update

---

Makefile

SFD-4119 Contract test script changes to load test services

SFD-4119 Contract test script changes to load test services

---

Makefile
test/contract/collections/FuzzySearchApiContractTests_collection.json

SFD-4194 Contract tests included for error handling changes

SFD-4194 Contract tests included for error handling changes

---

application/app/src/main/java/uk/nhs/digital/uec/api/authentication/constants/MockAuthenticationConstants.java
application/app/src/main/java/uk/nhs/digital/uec/api/service/impl/ExternalApiHandshakeService.java
application/app/src/main/resources/application.yaml
application/app/src/test/java/uk/nhs/digital/uec/api/service/ExternalApiHandshakeServiceTest.java

SFD-4208 Authentication from fuzzy to postcode for non prod env

SFD-4208 Authentication from fuzzy to postcode for non prod env

---

build/automation/var/profile/dev.mk

SFD-XXXX Changes in dev profile to connect mock PCA url

SFD-XXXX Changes in dev profile to connect mock PCA url

---

application/app/src/main/java/uk/nhs/digital/uec/api/interceptor/MDCInterceptor.java
application/app/src/main/resources/application.yaml
application/app/src/test/resources/logback-test.xml

SFD-4955 Update config to support Json format in logs

---

Makefile
build/automation/lib/docker.mk
build/jenkins/build/build.Jenkinsfile
build/jenkins/demo/demo-deployment.Jenkinsfile
build/jenkins/dev/dev-deployment.Jenkinsfile
build/jenkins/perf/perf-deployment.Jenkinsfile
build/jenkins/prod/prod-deployment.Jenkinsfile
build/jenkins/staging/staging-deployment.Jenkinsfile

1. Enables building on slave nodes
2. Prevents using `latest` as the IMAGE_TAG for deployments

SFD-5729 Prevent image tag latest

---

.github/dependabot.yml
application/app/pom.xml
application/app/src/main/java/uk/nhs/digital/uec/api/authentication/cognito/CognitoIdpServiceImpl.java
application/app/src/main/java/uk/nhs/digital/uec/api/service/impl/ApiUtilsService.java
application/app/src/main/java/uk/nhs/digital/uec/api/service/impl/LocationService.java
application/app/src/test/java/uk/nhs/digital/uec/api/authentication/localstub/LocalAmazonCognitoIdentityClientStubTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/repository/ServiceRepositoryTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/service/FuzzyServiceSearchServiceTest.java
application/app/src/test/java/uk/nhs/digital/uec/api/service/LocationServiceTest.java
build/automation/lib/java.mk

**https://nhsd-jira.digital.nhs.uk/browse/SFD-5841**
1. Update Java version from 16 to 17 (This is the minimum requirement for the future upgrade to spring boot 3.0)
2. Made a few changes due to the above java upgrade
3. Configure dependabot to update dependencies once in a month (It only raises the PR for us)

SFD-5841 Configure dependabot and upgrade from java 16 to 17

---

infrastructure/stacks/firewall/waf.tf

Removed terraform configuration sending firewall logs to firehose which is then logged to splunk

 Removed firewal logs config

---

application/app/src/main/java/uk/nhs/digital/uec/api/util/WebClientUtil.java
build/jenkins/build/build.Jenkinsfile

Applied the filter in the query parameter like the one below.
OData 3.0 (Current version)
OrganisationTypeId  eq 'OPT' or OrganisationTypeId  eq 'HOS' or OrganisationTypeId  eq 'DEN' or OrganisationTypeId  eq 'CLI' or OrganisationTypeId  eq 'PHA' or OrganisationTypeId  eq 'GPB'
OData 4.0
OrganisationTypeId in ('OPT','HOS','DEN','CLI','PHA','GPB')

SFD-6455 Apply filter for quick search in  NHS Choices API
